services:
  backend:
    build:
      context: .
      dockerfile: mlwarden/backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/data

volumes:
  backend-data:
